<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="F_CounterNegativeOverflow" Id="{92b9c22e-91a6-4220-928a-ec1733f656db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_CounterNegativeOverflow : BOOL
VAR_INPUT
	COUNTERVALUE	: UINT;	
	ValueToSet		: REFERENCE TO UINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

]]></ST>
    </Implementation>
    <LineIds Name="F_CounterNegativeOverflow">
      <LineId Id="10" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>