<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="F_Homing" Id="{306e44f6-bc33-4124-bfd9-c6ad82f7dfc7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Homing : BOOL
VAR
	LoopCount	: INT := 2000;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="F_Homing">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>